### PR TITLE
Support new Battery Doorbell device

### LINKED ISSUE #473: Update motion detection support
The 2024 Doorbell (device kind `df_doorbell_clownfish`) supports motion detection and should be added to the supported devices.
I tested it on my local branch and it works just fine.

### PR DESCRIPTION
**Pull request by dan5py**
Updates motion detection support for doorbell  (Fixes #473)

kind: `df_doorbell_clownfish`

### CODE REVIEW

**Comment by dan5py** [comment]
Not sure if its a new family, the Ring website marks it as a "2024 model". (btw this is the battery doorbell)

**Comment by dan5py** [comment]
Maybe it's better to list it under `DOORBELL_KINDS` instead?

**Comment by sdb9696** [comment]
In the device health settings what’s the product name?

**Comment by dan5py** [comment]
Battery Doorbell

**Comment by sdb9696** [comment]
It does seem to be a new product range their calling Battery Doorbell. Could you create a new group DOORBELL_BATTERY_KINDS that returns a model name of "Battery Doorbell" and put it in there?

**Review by sdb9696 — APPROVED** [review]
LGTM, thanks @dan5py!

**Pull request merged**
